defmodule Mix.Tasks.Mirai.Setup do
  @shortdoc "Interactive first-time onboarding wizard for Mirai"

  use Mix.Task

  @impl Mix.Task
  def run(_) do
    banner()

    # ── Step 1: Authentication ──
    section("STEP 1 — Authentication")
    admin_id = prompt("Enter your Telegram User ID (locks you as System Admin)")

    # ── Step 2: Telegram Bot ──
    section("STEP 2 — Telegram Bot")
    telegram_token = prompt("Paste your Telegram Bot Token (from @BotFather)")

    # ── Step 3: AI Provider ──
    section("STEP 3 — AI Provider")
    provider = choose("Which LLM provider do you want to use?", [
      {"Anthropic", "anthropic"},
      {"OpenRouter (supports 100+ models)", "openrouter"}
    ])

    {anthropic_key, openrouter_key, openrouter_model} =
      case provider do
        "anthropic" ->
          key = prompt("Enter your Anthropic API Key")
          {key, "", ""}

        "openrouter" ->
          key = prompt("Enter your OpenRouter API Key")

          Mix.shell().info("")
          Mix.shell().info("  Popular models:")
          Mix.shell().info("    • anthropic/claude-sonnet-4")
          Mix.shell().info("    • google/gemini-2.5-pro")
          Mix.shell().info("    • meta-llama/llama-4-maverick")
          Mix.shell().info("")

          model = prompt_default("Which model? [anthropic/claude-sonnet-4]", "anthropic/claude-sonnet-4")
          {"", key, model}
      end

    # ── Step 4: Web Dashboard ──
    section("STEP 4 — Web Dashboard")
    port = prompt_default("Dashboard port [4000]", "4000")

    # ── Generate Files ──
    File.mkdir_p!("data")

    # Build .env (only non-empty keys)
    env_lines = [
      "# Generated by mix mirai.setup",
      "TELEGRAM_BOT_TOKEN=#{telegram_token}",
      if(anthropic_key != "", do: "ANTHROPIC_API_KEY=#{anthropic_key}"),
      if(openrouter_key != "", do: "OPENROUTER_API_KEY=#{openrouter_key}"),
      if(openrouter_model != "", do: "OPENROUTER_MODEL=#{openrouter_model}"),
      "PORT=#{port}"
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")

    File.write!("data/.env", env_lines <> "\n")

    config_content = """
    # Generated by mix mirai.setup
    system:
      workspace_dir: "~/.mirai/workspace"
      log_level: "info"
      admin_user_id: #{admin_id}

    agents:
      default_provider: "#{provider}"
      max_recursion_depth: 10

    mesh:
      node_name: "mirai_primary"
      cluster_strategy: "epmd"
    """

    File.write!("data/config.yml", config_content)

    # Write root .env for docker-compose port mapping (NOT secrets)
    File.write!(".env", """
    # Used by docker-compose for port mapping (NOT for secrets)
    # Secrets are in data/.env
    PORT=#{port}
    """)

    # ── Done ──
    Mix.shell().info("")
    Mix.shell().info("  ╔══════════════════════════════════════════╗")
    Mix.shell().info("  ║  ✅  Setup complete!                     ║")
    Mix.shell().info("  ║                                          ║")
    Mix.shell().info("  ║  Config  → data/config.yml               ║")
    Mix.shell().info("  ║  Secrets → data/.env                     ║")
    Mix.shell().info("  ║                                          ║")
    Mix.shell().info("  ║  Run: docker-compose up                  ║")
    Mix.shell().info("  ╚══════════════════════════════════════════╝")
    Mix.shell().info("")
  end

  # ── UI Helpers ──

  defp banner do
    Mix.shell().info("")
    Mix.shell().info("  ╔══════════════════════════════════════════╗")
    Mix.shell().info("  ║         🤖  Mirai Setup Wizard           ║")
    Mix.shell().info("  ║                                          ║")
    Mix.shell().info("  ║  All configs saved to ./data/            ║")
    Mix.shell().info("  ╚══════════════════════════════════════════╝")
    Mix.shell().info("")
  end

  defp section(title) do
    Mix.shell().info("")
    Mix.shell().info("  ┌─ #{title} ─────────────────────────")
    Mix.shell().info("  │")
  end

  defp choose(question, options) do
    Mix.shell().info("  │  #{question}")
    Mix.shell().info("  │")

    options
    |> Enum.with_index(1)
    |> Enum.each(fn {{label, _val}, idx} ->
      Mix.shell().info("  │    [#{idx}] #{label}")
    end)

    Mix.shell().info("  │")
    input = Mix.shell().prompt("  │  Your choice >") |> String.trim()

    case Integer.parse(input) do
      {n, _} when n >= 1 and n <= length(options) ->
        {_label, val} = Enum.at(options, n - 1)
        val

      _ ->
        Mix.shell().info("  │  ⚠  Please enter a number between 1 and #{length(options)}")
        choose(question, options)
    end
  end

  defp prompt(label) do
    input = Mix.shell().prompt("  │  #{label} >") |> String.trim()

    if input == "" do
      Mix.shell().info("  │  ⚠  This field is required.")
      prompt(label)
    else
      input
    end
  end

  defp prompt_default(label, default) do
    input = Mix.shell().prompt("  │  #{label} >") |> String.trim()
    if input == "", do: default, else: input
  end
end
